sudo: required

language: node_js
node_js: "9"

services:
  - docker

jobs:
  include:
    - stage: build and test
      script:
        - export PATH=$PATH:`yarn bin`
        - yarn build
        - yarn test
    - stage: build docker image
      script:
        - docker build -t kabachook/telegram-pdf-bot
        - docker run kabachook/telegram-pdf-bot /bin/bash -c "cd /app;export PATH=$PATH:`yarn bin`;yarn test;"