sudo: required

language: node_js
node_js: "9"

services:
  - docker

jobs:
  include:
    - stage: build and test
      script:
        - yarn install
        - yarn build
        - yarn test
    - stage: build docker image
      script:
        - docker build -t kabachook/telegram-pdf-bot
        - docker run kabachook/telegram-pdf-bot /bin/sh -c "cd /app; yarn test;"