sudo: required

language: node_js
node_js: "9"

services:
  - docker

cache:
  npm: true

jobs:
  include:
    - stage: build and test
      script:
        - npm build
        - npm test
    - stage: build docker image
      script:
        - docker build -t kabachook/telegram-pdf-bot .
        - docker run kabachook/telegram-pdf-bot /bin/bash -c "cd /app;export PATH=$PATH:`yarn bin`;yarn test;"