sudo: required

language: node_js
node_js: "9"

services:
  - docker

cache:
  npm: true

jobs:
  include:
    - stage: build and test
      script:
        - export NODE_ENV=production
        - npx babel src -d dist
        - npx mocha -t 20000
    - stage: build docker image
      script:
        - docker build -t kabachook/telegram-pdf-bot .
        - docker run kabachook/telegram-pdf-bot /bin/sh -c "cd /app;NODE_ENV=production npx mocha -t 20000;"